### ISSUE TITLE
Can't instantiate emailinvest in lowercase in README and examples

### ISSUE THREAD

**Issue by javornikolov** [NEVUP-LTD/emailinvest-api#1]
The following in README doesn't work right now (9a78e53885e9ac97904ed2f2fb61354490468a71):
``` php
$ei = new api\emailinvest("YOUR_KEY", "YOUR_USERNAME", true);
```

It leads to error:
```
PHP Warning:  Uncaught Error: Class 'api\emailinvest' not found in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1
```

What seems to work is:
``` php
$ei = Emailinvest("YOUR_KEY", "YOUR_USERNAME", true);
```
I.e. drop the `api` namespace and use uppercase.

But I'm not sure what is it intended to be (the code in the examples is also in lowercase).

**Comment by ifkooo** [comment]
Thank you for that information.
We will fix soon as possible code.
Have a nice day!

**Comment by ifkooo** [comment]
Update:
We update our Readme and examples to use Uppercase.
Thank you again

**Comment by javornikolov** [comment]
Thank you!
